.\"
.\"     include-tidy -- #include tidier
.\"     include-tidy.5 manual page
.\"
.\"     Copyright (C) 2026  Paul J. Lucas
.\"
.\"     This program is free software: you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation, either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" ---------------------------------------------------------------------------
.\" define code-start macro
.de cS
.sp
.nf
.RS 5
.ft CW
..
.\" define code-end macro
.de cE
.ft 1
.RE
.fi
.if !'\\$1'0' .sp
..
.\" ---------------------------------------------------------------------------
.TH \f3include-tidy\fP 5 "March 31, 2026" "PJL TOOLS"
.SH NAME
include-tidy.toml \(em \f(CWinclude\P tidier configuration file
.SH DESCRIPTION
The
.B include-tidy.toml
file is used to configure
.BR include-tidy (1).
The file is ``lite'' version of TOML.
(See
.B CAVEATS
for unsupported TOML.)
The file is broken down into sections
(``tables'' in TOML parlance)
where each section is started by a line of the form:
.P
.RS 5
.RI [ table-name ]
.RE
.P
that is a left bracket,
a table name,
and a right bracket.
There must be
.I no
whitespace between the brackets.
.PP
A table name
is either a relative path of an include file
(what you would put between either the \f(CW""\fP
or \f(CW<>\fP in an \f(CW#include\fP directive,
e.g., \f(CWstdio.h\fP
or \f(CWsys/wait.h\fP)
or a symbol name,
e.g., \f(CWsize_t\fP.
Note that if a table name
contains a character other than
\f(CW[A-Za-z0-9_-.]\fP
(a letter, digit, underscore, dash, or dot),
then the table name
.I must
be quoted.
.SH EXAMPLE
.nf
.ft CW
[pjl_config.h]
proxy = [
    "attribute.h",
    "config.h"
]
.ft 1
.fi
.SH CAVEATS
.SS Unsupported TOML
The following parts of TOML are
.I not
supported
because they aren't needed
to configure
.BR include-tidy (1):
.sp
.PD 0
.IP \(bu 3
Array of tables.
.IP \(bu
Dates or times.
.IP \(bu
Floating-point numbers.
.IP \(bu
Inline tables.
.IP \(bu
UTF-8.
.PD
.SH AUTHOR
Paul J. Lucas
.RI < paul@lucasmail.org >
.SH SEE ALSO
.BR include-tidy (1)
.\" vim:set et sw=2 ts=2:
