##
#       include-tidy -- #include tidier
#       etc/config.toml -- default configuration file
#
#       Copyright (C) 2026  Paul J. Lucas
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

[include-tidy]
std-c-includes = [

  # Standard C <https://en.cppreference.com/w/c/header.html>
  "assert.h",
  "complex.h",
  "ctype.h",
  "errno.h",
  "fenv.h",
  "float.h",
  "inttypes.h",
  "iso646.h",
  "limits.h",
  "locale.h",
  "math.h",
  "setjmp.h",
  "signal.h",
  "std*.h",
  "string.h",
  "tgmath.h",
  "time.h",
  "wchar.h",
  "wctype.h",

  # Standard C11 <https://en.cppreference.com/w/c/header.html>
  "threads.h",
  "uchar.h",

  # POSIX <https://pubs.opengroup.org/onlinepubs/9699919799/idx/head.html>
  "aio.h",
  "arpa/inet.h",
  "cpio.h",
  "dirent.h",
  "dlfcn.h",
  "fcntl.h",
  "fmtmsg.h",
  "fnmatch.h",
  "ftw.h",
  "glob.h",
  "grp.h",
  "iconv.h",
  "langinfo.h",
  "libgen.h",
  "monetary.h",
  "mqueue.h",
  "ndbm.h",
  "netdb.h",
  "net/in.h",
  "netinet6/in.h",
  "netinet/in.h",
  "nl_types.h",
  "poll.h",
  "pthread.h",
  "pwd.h",
  "regex.h",
  "sched.h",
  "search.h",
  "semaphore.h",
  "spawn.h",
  "strings.h",
  "stropts.h",
  "sys/ipc.h",
  "syslog.h",
  "sys/mman.h",
  "sys/msg.h",
  "sys/resource.h",
  "sys/select.h",
  "sys/sem.h",
  "sys/shm.h",
  "sys/socket.h",
  "sys/stat.h",
  "sys/statvfs.h",
  "sys/time.h",
  "sys/times.h",
  "sys/types.h",
  "sys/uio.h",
  "sys/un.h",
  "sys/utsname.h",
  "sys/wait.h",
  "tar.h",
  "termios.h",
  "trace.h",
  "ulimit.h",
  "unistd.h",
  "utime.h",
  "utmpx.h",
  "wordexp.h",

  # BSD, macOS
  "sysexits.h",

  # Other Unix
  "curses.h",
  "linux/*",
  "ncurses.h",
  "term.h",
  "X11/*",

  # Popular 3rd-party libraries
  "openssl/*",
]

std-cpp-includes = [
  "algorithm",
  "any",
  "array",
  "atomic",
  "barrier",
  "bit",
  "bitset",
  "cassert",
  "cctype",
  "cerrno",
  "cfenv",
  "cfloat",
  "charconv",
  "chrono",
  "cinttypes",
  "climits",
  "clocale",
  "cmath",
  "codecvt",
  "compare",
  "complex",
  "concepts",
  "condition_variable",
  "contracts",
  "coroutine",
  "csetjmp",
  "csignal",
  "cstd*",
  "cstring",
  "ctime",
  "cuchar",
  "cwchar",
  "cwctype",
  "debugging",
  "deque",
  "exception",
  "execution",
  "expected",
  "filesystem",
  "flat_map",
  "flat_set",
  "format",
  "forward_list",
  "fstream",
  "functional",
  "future",
  "generator",
  "hazard_pointer",
  "hive",
  "initializer_list",
  "inplace_vector",
  "iomanip",
  "ios",
  "iosfwd",
  "iostream",
  "istream",
  "iterator",
  "latch",
  "limits",
  "linalg",
  "list",
  "locale",
  "map",
  "mdspan",
  "memory",
  "memory_resource",
  "mutex",
  "new",
  "numbers",
  "numeric",
  "optional",
  "ostream",
  "print",
  "queue",
  "random",
  "ranges",
  "ratio",
  "rcu",
  "regex",
  "scoped_allocator",
  "semaphore",
  "set",
  "shared_mutex",
  "simd",
  "source_location",
  "span",
  "spanstream",
  "sstream",
  "stack",
  "stacktrace",
  "stdexcept",
  "stdfloat",
  "stop_token",
  "streambuf",
  "string",
  "string_view",
  "strstream",
  "syncstream",
  "system_error",
  "text_encoding",
  "thread",
  "tuple",
  "type_traits",
  "typeindex",
  "typeinfo",
  "unordered_map",
  "unordered_set",
  "utility",
  "valarray",
  "variant",
  "vector",
  "version",
]

[free]
includes = "stdlib.h"

# NULL is declared in all of these, so any one is sufficient.
[NULL]
includes = [
  "locale.h",
  "stddef.h",
  "stdio.h",
  "stdlib.h",
  "string.h",
  "time.h",
  "wchar.h",
]

# These extern variables are used both by getopt(3), which is declared in
# unistd.h, and getopt_long(3), which is declared in getopt.h.  Therefore,
# including either one is sufficient.
[optarg]
includes = [ "getopt.h", "unistd.h" }
[opterr]
includes = [ "getopt.h", "unistd.h" }
[optind]
includes = [ "getopt.h", "unistd.h" }
[optopt]
includes = [ "getopt.h", "unistd.h" }
[optreset]
includes = [ "getopt.h", "unistd.h" }

# size_t is declared in all of these, so any one is sufficient.
[size_t]
includes = [
  "stddef.h",
  "stdio.h",
  "stdlib.h",
  "string.h",
  "time.h",
  "uchar.h",
  "wchar.h",
]

# ssize_t is declared in all of these, so any one is sufficient.
[ssize_t]
includes = [
  "stddef.h",
  "stdio.h",
  "stdlib.h",
  "string.h",
  "time.h",
  "uchar.h",
  "wchar.h",
]

[time_t]
includes = "time.h"

# vim:se et sw=2 ts=2:
