##
#       include-tidy -- #include tidier
#       include-tidy.toml -- default configuration file
#
#       Copyright (C) 2026  Paul J. Lucas
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

[include-tidy]
std-c-includes = [
  "aio.h",
  "arpa/*",
  "assert.h",
  "complex.h",
  "cpio.h",
  "ctype.h",
  "dirent.h",
  "dlfcn.h",
  "errno.h",
  "fcntl.h",
  "fenv.h",
  "float.h",
  "fmtmsg.h",
  "fnmatch.h",
  "ftw.h",
  "glob.h",
  "grp.h",
  "iconv.h",
  "inttypes.h",
  "iso646.h",
  "langinfo.h",
  "libgen.h",
  "limits.h",
  "linux/*",
  "locale.h",
  "math.h",
  "monetary.h",
  "mqueue.h",
  "ndbm.h",
  "net/*",
  "netdb.h",
  "netinet/*",
  "netinet6/*",
  "nl_types.h",
  "openssl/*",
  "poll.h",
  "pthread.h",
  "pwd.h",
  "regex.h",
  "sched.h",
  "search.h",
  "semaphore.h",
  "setjmp.h",
  "signal.h",
  "spawn.h",
  "std*.h",
  "string.h",
  "strings.h",
  "stropts.h",
  "sys/*",
  "sysexits.h",
  "syslog.h",
  "tar.h",
  "termios.h",
  "tgmath.h",
  "threads.h",
  "time.h",
  "trace.h",
  "uchar.h",
  "ulimit.h",
  "unistd.h",
  "utime.h",
  "utmpx.h",
  "wchar.h",
  "wctype.h",
  "wordexp.h",
  "X11/*",
]

std-cpp-includes = [
  "algorithm",
  "any",
  "array",
  "atomic",
  "barrier",
  "bit",
  "bitset",
  "cassert",
  "cctype",
  "cerrno",
  "cfenv",
  "cfloat",
  "charconv",
  "chrono",
  "cinttypes",
  "climits",
  "clocale",
  "cmath",
  "codecvt",
  "compare",
  "complex",
  "concepts",
  "condition_variable",
  "contracts",
  "coroutine",
  "csetjmp",
  "csignal",
  "cstd*",
  "cstring",
  "ctime",
  "cuchar",
  "cwchar",
  "cwctype",
  "debugging",
  "deque",
  "exception",
  "execution",
  "expected",
  "filesystem",
  "flat_map",
  "flat_set",
  "format",
  "forward_list",
  "fstream",
  "functional",
  "future",
  "generator",
  "hazard_pointer",
  "hive",
  "initializer_list",
  "inplace_vector",
  "iomanip",
  "ios",
  "iosfwd",
  "iostream",
  "istream",
  "iterator",
  "latch",
  "limits",
  "linalg",
  "list",
  "locale",
  "map",
  "mdspan",
  "memory",
  "memory_resource",
  "mutex",
  "new",
  "numbers",
  "numeric",
  "optional",
  "ostream",
  "print",
  "queue",
  "random",
  "ranges",
  "ratio",
  "rcu",
  "regex",
  "scoped_allocator",
  "semaphore",
  "set",
  "shared_mutex",
  "simd",
  "source_location",
  "span",
  "spanstream",
  "sstream",
  "stack",
  "stacktrace",
  "stdexcept",
  "stdfloat",
  "stop_token",
  "streambuf",
  "string",
  "string_view",
  "strstream",
  "syncstream",
  "system_error",
  "text_encoding",
  "thread",
  "tuple",
  "type_traits",
  "typeindex",
  "typeinfo",
  "unordered_map",
  "unordered_set",
  "utility",
  "valarray",
  "variant",
  "vector",
  "version",
]

[NULL]
includes = [
  "locale.h",
  "stddef.h",
  "stdio.h",
  "stdlib.h",
  "string.h",
  "time.h",
  "wchar.h",
]

[size_t]
includes = [
  "stddef.h",
  "stdio.h",
  "stdlib.h",
  "string.h",
  "time.h",
  "uchar.h",
  "wchar.h",
]

# vim:se et sw=2 ts=2:
