.\"
.\"     include-tidy -- #include tidier
.\"     include-tidy.1: manual page
.\"
.\"     Copyright (C) 2026  Paul J. Lucas
.\"
.\"     This program is free software: you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation, either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" ---------------------------------------------------------------------------
.\" define code-start macro
.de cS
.sp
.nf
.RS 5
.ft CW
..
.\" define code-end macro
.de cE
.ft 1
.RE
.fi
.if !'\\$1'0' .sp
..
.\" ---------------------------------------------------------------------------
.TH \f3include-tidy\fP 1 "March 3, 2026" "PJL TOOLS"
.SH NAME
include-tidy \- include tidier
.SH SYNOPSIS
.B include-tidy
.BI [ options ]
.B source-file
.SH DESCRIPTION
.B include-tidy
is ...

.SH OPTIONS
An option argument
.I f
means
.IR file ,
.I n
means
.IR "unsigned integer" ,
and
.I s
means
.IR string .
.TP 5
.BR \-\-help " | " \-h
Prints a help message
for command-line options
and exits.
.TP
.BR \-\-version " | " \-v
Prints the version number
and exits.
If given twice,
additionally prints
the set of configure
feature & package options.
.SH EXIT STATUS
.PD 0
.IP 0
Success.
.IP 64
Command-line usage error.
.IP 66
Open file error.
.IP 69
A system resource is not available, e.g., a UTF-8 locale.
.IP 70
Internal software error.
(Please report the bug.)
.IP 71
System error.
.IP 73
Create file error.
.IP 74
I/O error.
.IP 78
Configuration file error.
.PD
.SH ENVIRONMENT
.TP
.B HOME
Used to locate a default configuration file
under the user's home directory.
If unset,
the home directory is obtained from the password database entry
for the effective user.
If that fails,
no default configuration file
under the user's home directory
is read.
.TP
.B XDG_CONFIG_DIRS
If set to a colon separated list of paths,
then for each
.I path
in it,
the first of
.IB path /wrap
to exist
and be readable
is used as the configuration file
(see
.BR wraprc (5)).
.TP
.B XDG_CONFIG_HOME
If set to a path
of a directory
and
.B $XDG_CONFIG_HOME/wrap
exists and is readable,
then that used as the configuration file
(see
.BR wraprc (5)).
.SH FILES
.TP
.B $XDG_CONFIG_HOME/include-tidy
.PD 0
.TP
.B ~/.config/include-tidy
.TP
.B /etc/xdg/include-tidy
.PD
The default configuration file.
.SH AUTHOR
Paul J. Lucas
.RI < paul@lucasmail.org >
.SH SEE ALSO
.BR sysexits (3),
.\" vim:set et sw=2 ts=2:
